### ISSUE TITLE
RecyclerView:IndexOutOfBoundsException

### ISSUE THREAD

**Issue by rusmichal** [xyxyLiu/SwipeRefreshLayout#11]
Hello, 

I use your library to refresh `RecyclerView` but I got crash. I am not sure if it related with your library. Android 6.0, Library version 1.1.1

```
Fatal Exception: java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 1(offset:2).state:2
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5011)
       at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4967)
       at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2029)
       at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1414)
       at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1377)
       at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:578)
       at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3266)
       at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3122)
       at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3568)
       at android.view.View.layout(View.java:17025)
       at android.view.ViewGroup.layout(ViewGroup.java:5579)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1189)
       at android.view.View.layout(View.java:17025)
       at android.view.ViewGroup.layout(ViewGroup.java:5579)
       at com.reginald.swiperefresh.CustomSwipeRefreshLayout.onLayout(CustomSwipeRefreshLayout.java:657)
```

**Comment by xyxyLiu** [comment]
It seems like something error with the your RecyclerView
[http://stackoverflow.com/questions/30220771/recyclerview-inconsistency-detected-invalid-item-position](url)

**Comment by rusmichal** [comment]
Probably You are right. Because I found workaround. I create empty adapter
